### PR TITLE
override head

### PR DESCRIPTION
**Pull request by maelle**
Related to #55 (that I'd like to keep open depending on https://github.com/r-lib/pkgdown/issues/1966)

The head.html is the same as pkgdown minus the MathJax lines.

### CODE REVIEW

**Comment by jeroen** [comment]
Hmm yes it is unfortunate now we have to maintain this file separately from upstream pkgdown. It would be much nicer if we can opt-out in pkgdown itself.

**Comment by maelle** [comment]
I think we can have this for now and simplify later if that becomes possible?

**Comment by jeroen** [comment]
Let's at least take out the GA part then, such that we don't end up with trackers on our domain.

**Comment by jeroen** [comment]
Can we look at the old head.html here: https://github.com/ropensci-org/rotemplate/blob/bs3-final/inst/pkgdown/templates/head.html

I think we also need to port the favicon lines, because we use hardcoded ropensci favicons instead of ones provided by the package, e.g. https://docs.ropensci.org/apple-touch-icon.png and so on.

Perhaps we should also be setting the twitter cards and so on in our template?

**Comment by maelle** [comment]
I'll handle the opengraph stuff from our wrapper.

**Comment by maelle** [comment]
actually the opengraph automatic stuff is already ok (from pkgdown itself)

**Comment by jeroen** [comment]
Thanks!

**Pull request merged**
