### PR TITLE
add logo everywhere

### LINKED ISSUE #21: Add twitter / facebook thumbnail
Test with https://cards-dev.twitter.com/validator

### PR DESCRIPTION
**Pull request by maelle**
Fix #21

Inject the logo so that pkgdown uses it everywhere (in head metadata but also all pages).
Now, the problem is that if you use `build_ropensci_docs()` locally you end up with the logo in man/figures.

### CODE REVIEW

**Comment by maelle** [comment]
Maybe too much :thinking:

**Comment by jeroen** [comment]
What does this do for packages that have their own logo in the readme such as https://docs.ropensci.org/targets/

**Comment by maelle** [comment]
Nothing because `find.logo(path)` is not NULL.

And pkgdown strips the logo in the README https://github.com/r-lib/pkgdown/blob/dcec859cab08ff8852f5ee5ab09f3f57ec038805/R/tweak-page.R#L85

**Comment by jeroen** [comment]
We should test this on a few ropensci repos with actual logo's because when I implemented this, that part in pkgdown didn't work very well. Some ropensci packages my have logo's in slightly different ways.

Also note that the old code is using `find_old_footer_banner()` to remove a legacy banner which we used to add to readme files (the banner is both ugly and redundant on docs.ropensci.org).

**Comment by maelle** [comment]
I'll come back to this next week or later, but listing a few packages with logos

* https://docs.ropensci.org/auk/
* https://docs.ropensci.org/bomrang/
* https://docs.ropensci.org/c14bazAAR/
* https://docs.ropensci.org/drake/
* https://docs.ropensci.org/eia/
* https://docs.ropensci.org/exoplanets/
* https://docs.ropensci.org/medrxivr/
* https://docs.ropensci.org/nasapower/
* https://docs.ropensci.org/nbaR/
* https://docs.ropensci.org/opentripplanner/
* https://docs.ropensci.org/outsider/

**Comment by jeroen** [comment]
Does this PR fix https://docs.ropensci.org/tradestatistics/ ?

**Comment by maelle** [comment]
> Does this PR fix docs.ropensci.org/tradestatistics ?

No I think that logo does not live at a path where pkgdown would find it.

Furthermore regarding the sponsor image, should it be tweaked by the author so that it's not at the top?

**Comment by maelle** [comment]
targets website would look fine with this.

**Comment by maelle** [comment]
@jeroen would you mind having a look at this again? Thank you!

**Comment by jeroen** [comment]
You have tested this on a few sites with custom logos, right?

**Pull request merged**
