### PR TITLE
Reduce padding of sidebar titles (fix #8) 

### LINKED ISSUE #8: toc style
I think the TOC for articles is still a bit large for example [magick vignette](https://maelle.github.io/magick/articles/intro.html). The tidyverse one seems a lot smaller but I'm not sure we can copy that: https://tidyr.tidyverse.org/dev/articles/pivot.html

### PR DESCRIPTION
**Pull request by Bisaloo**
This seems to work on my computer. I can obviously amend this if you'd like. Please let me know ;)

### CODE REVIEW

**Comment by Bisaloo** [comment]
Oh, I just realised that's what you did as well @maelle. You didn't find this solution satisfying?

(preview URL has changed to https://ropensci.github.io/rotemplate/articles/test.html)

**Comment by Bisaloo** [comment]
Here is another solution. Please let me know what you think!

**Comment by maelle** [comment]
Thanks! Is this related to #8?

**Comment by Bisaloo** [comment]
@maelle, yes! I wrote it in the (first) commit message :wink:

**Comment by maelle** [comment]
@jeroen any opinion? :-)

**Pull request closed without merging**
